Set SLURM handle signals.

  | Name  | Type | Params
-------------------------------
0 | model | Glow | 267 M 
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    main()
  File "train.py", line 215, in main
    trainer.fit(glow_light)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_hpc_accelerator.py", line 63, in train
    self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/accelerators/ddp_hpc_accelerator.py", line 176, in ddp_train
    self.trainer.train_loop.setup_training(model)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 174, in setup_training
    self.trainer.checkpoint_connector.restore_weights(model)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 75, in restore_weights
    self.restore(self.trainer.resume_from_checkpoint, on_gpu=self.trainer.on_gpu)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 100, in restore
    checkpoint = pl_load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py", line 31, in load
    with fs.open(path_or_url, "rb") as f:
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/fsspec/spec.py", line 886, in open
    f = self._open(
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/fsspec/implementations/local.py", line 115, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/fsspec/implementations/local.py", line 197, in __init__
    self._open()
  File "/home/mvpavlukhin/.conda/envs/speech2face/lib/python3.8/site-packages/fsspec/implementations/local.py", line 202, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mvpavlukhin/speech2face/output/epoch=8.ckpt'
